version: '3.8'
services:
  db:
    image: mysql:8.0.11
    container_name: docker-MYSQL
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - docker-service
    volumes:
      - mysql-data:/data/db
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD' ]
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - docker-service
    depends_on:
      - db
  prod:
    container_name: prod
    build:
      context: .
      target: production
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - docker-service
    restart: 'unless-stopped'
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - db
networks:
  docker-service:
    driver: bridge
volumes:
  mysql-data:
    driver: local